[package]
name = "edi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
libc = "0.2.161"
termios = "0.3.3"
thiserror = "2.0.1"
timeout-readwrite = "0.4.0"

[dev-dependencies]
rand = "0.8.5"
